{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.5.3/lib-0.5.3.module",
    "group": "nz.eloque.compose-kit",
    "module": "lib",
    "version": "0.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.5.3.aar",
          "size": 301173,
          "sha512": "a2f1b0d720ab56289d967b7c38247a9e2bed2694610fc1f14388f010ebbc7031b4b4812d0659ce9515829ac11f22b831c5da27dba7353efdb86fd55dee937b02",
          "sha256": "62e29cb0899b53449d9e4d85196640bf6be6052a8d2faa1722dd247bc8395db0",
          "sha1": "068f59d1ef20ef7e9cf807e4c69f45de0e7af223",
          "md5": "a9315774144672038436383f2d36e230"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha24"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.5.3.aar",
          "size": 301173,
          "sha512": "a2f1b0d720ab56289d967b7c38247a9e2bed2694610fc1f14388f010ebbc7031b4b4812d0659ce9515829ac11f22b831c5da27dba7353efdb86fd55dee937b02",
          "sha256": "62e29cb0899b53449d9e4d85196640bf6be6052a8d2faa1722dd247bc8395db0",
          "sha1": "068f59d1ef20ef7e9cf807e4c69f45de0e7af223",
          "md5": "a9315774144672038436383f2d36e230"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lib-android-0.5.3-sources.jar",
          "url": "lib-android-0.5.3-sources.jar",
          "size": 38754,
          "sha512": "46fcfb4283a74794a3b57d200afa2142ae742dcf3be77ce23cb3753317656f1eed5e8509f0d4fabe339b438eaf1ed24a23c61d03e9e4284a9f0f2014e5d80b90",
          "sha256": "6c8729ba1a8a5c2463808a12f42d1a1ba117a762a0fa2677ba80c8c6683f5436",
          "sha1": "b06cdb27a51a2c3209b6108be70e5827bf782184",
          "md5": "c3b90bf21cb7f96fd4ecd753793921cd"
        }
      ]
    }
  ]
}
