{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.3.0/lib-0.3.0.module",
    "group": "nz.eloque.compose-kit",
    "module": "lib",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.3.0.aar",
          "size": 293157,
          "sha512": "53e8768a481ea3349e365d59c24c4d831a0cc0c849c787956474d383e7c01f6567c0b5705a9925f7f5ef4fe93226f6832dbc5d45b67fad1773ccf214bbf56ee5",
          "sha256": "fd9a7d7420f949718f47c700268ac76b5b7328396581bec0c2a619ae5d152274",
          "sha1": "b64e3a62b647152d0059ee1819157fdb3b87beff",
          "md5": "b8521689e6a6ff852039b539905cad51"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha22"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.3.0.aar",
          "size": 293157,
          "sha512": "53e8768a481ea3349e365d59c24c4d831a0cc0c849c787956474d383e7c01f6567c0b5705a9925f7f5ef4fe93226f6832dbc5d45b67fad1773ccf214bbf56ee5",
          "sha256": "fd9a7d7420f949718f47c700268ac76b5b7328396581bec0c2a619ae5d152274",
          "sha1": "b64e3a62b647152d0059ee1819157fdb3b87beff",
          "md5": "b8521689e6a6ff852039b539905cad51"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lib-android-0.3.0-sources.jar",
          "url": "lib-android-0.3.0-sources.jar",
          "size": 38010,
          "sha512": "85fbdc70ee56407dee20d8bd8e0e121a3a58bb6d64f8df4928a1e0b4deb5b7447e30f79234a9019f64d05fe9828b59a9615ae9ffcb874466fd20f6809f6935e5",
          "sha256": "de48ce77e6796c72fbd60a2472ba58fec8c2aee31f7651b45277158db92c4023",
          "sha1": "65532d88ee4610ae8550794cbefc13da167ff16a",
          "md5": "da26af8d62e71512e7404b4c5300d3d9"
        }
      ]
    }
  ]
}
