{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.0/lib-0.1.0.module",
    "group": "nz.eloque.compose-kit",
    "module": "lib",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.1.0.aar",
          "size": 279208,
          "sha512": "0742180e34ad7fa2f30c33022a10efc4a0ec92ca7a02a0f082dfbb5d100909984f5095b8ea0623bf89f06380a0a7717be53fbe21e7fafe174602fdf81b89f95a",
          "sha256": "38ce97e30b86f36ae522695b5e5cc3515d1c6e697b5891ec3a4f267e8d6ed3fb",
          "sha1": "4a49bf403928cc5ab07df51fe29a134e8a5ee20c",
          "md5": "fcbfbc51ca13457f6061d1d1198b654f"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha21"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.1.0.aar",
          "size": 279208,
          "sha512": "0742180e34ad7fa2f30c33022a10efc4a0ec92ca7a02a0f082dfbb5d100909984f5095b8ea0623bf89f06380a0a7717be53fbe21e7fafe174602fdf81b89f95a",
          "sha256": "38ce97e30b86f36ae522695b5e5cc3515d1c6e697b5891ec3a4f267e8d6ed3fb",
          "sha1": "4a49bf403928cc5ab07df51fe29a134e8a5ee20c",
          "md5": "fcbfbc51ca13457f6061d1d1198b654f"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lib-android-0.1.0-sources.jar",
          "url": "lib-android-0.1.0-sources.jar",
          "size": 35016,
          "sha512": "051c1b2271309e1d7ac6a2f59a69f997a2ad03397c431652e404e70da305ecdf1b7137b80c4bb855d257de6d370a9de1a70175e9387768e1f587417ac55488dd",
          "sha256": "8a3a233f4c65f9d3fc1e776e0f522a2693e217947cba5fa614f2a00629119a15",
          "sha1": "5bbc9e1e359cadecebc2d9e8108e17985f32eb98",
          "md5": "3594343e4b1260e24567469817737598"
        }
      ]
    }
  ]
}
