{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.5.5/lib-0.5.5.module",
    "group": "nz.eloque.compose-kit",
    "module": "lib",
    "version": "0.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.5.5.aar",
          "size": 318250,
          "sha512": "a0264c9c80cea5398c2785db20b90f2a8adcb163792704a00e89af285f7bdadd5241c73a820b28a806202024379f6c7a8fc363afb08694128de3b60a33a3a70f",
          "sha256": "9bf56a323cbb70fb8777973c6030722811a1671185f8623c9c0f8e314f16337a",
          "sha1": "f27d5e34ac9f1bf1a80ae253ff5c5bb9c737e9c0",
          "md5": "893e6e12a8279593beebeaebe463475f"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha24"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.5.5.aar",
          "size": 318250,
          "sha512": "a0264c9c80cea5398c2785db20b90f2a8adcb163792704a00e89af285f7bdadd5241c73a820b28a806202024379f6c7a8fc363afb08694128de3b60a33a3a70f",
          "sha256": "9bf56a323cbb70fb8777973c6030722811a1671185f8623c9c0f8e314f16337a",
          "sha1": "f27d5e34ac9f1bf1a80ae253ff5c5bb9c737e9c0",
          "md5": "893e6e12a8279593beebeaebe463475f"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lib-android-0.5.5-sources.jar",
          "url": "lib-android-0.5.5-sources.jar",
          "size": 40256,
          "sha512": "2f2033abc0bce14504a57aef143818bbf11a2877f68e1a3204d717d976389c764f535367f885e3a4679054a294e1dc69ba80aa66498dc80d68aece0de9f1da11",
          "sha256": "7303377eb2261009148cfcb238087179291e18fede3a9526df81242c2ee5f512",
          "sha1": "e5fd379bb3b48eab7dbd2f80c801b2b436d79682",
          "md5": "ffcd822fb4d20496056cb3a818fc5be2"
        }
      ]
    }
  ]
}
