{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.5.8/lib-0.5.8.module",
    "group": "nz.eloque.compose-kit",
    "module": "lib",
    "version": "0.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.5.8.aar",
          "size": 318469,
          "sha512": "1b0bea9cf300b398faded10ff8234e0f1917a9daa8361dc21025fc99901dc931e8bc2f52fbde5a87bca555b3ea39507696fde3fc410ca777ce3fe64cd8bc73ec",
          "sha256": "5c0252a2f599ff7b1a86a4ed7146d9c8ba248f63dbb123be0b95ba67bcb47f2b",
          "sha1": "a883ad9bc637101a76eda245f6d1477ca96e057c",
          "md5": "709d0250151ddabe99cece190d6bdcd8"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha24"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.5.8.aar",
          "size": 318469,
          "sha512": "1b0bea9cf300b398faded10ff8234e0f1917a9daa8361dc21025fc99901dc931e8bc2f52fbde5a87bca555b3ea39507696fde3fc410ca777ce3fe64cd8bc73ec",
          "sha256": "5c0252a2f599ff7b1a86a4ed7146d9c8ba248f63dbb123be0b95ba67bcb47f2b",
          "sha1": "a883ad9bc637101a76eda245f6d1477ca96e057c",
          "md5": "709d0250151ddabe99cece190d6bdcd8"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lib-android-0.5.8-sources.jar",
          "url": "lib-android-0.5.8-sources.jar",
          "size": 40268,
          "sha512": "2822a2869718df722b0b7a9abf482a280479d34772c8e79e3846610e3b4a34f2604d305ee8060def50b30769a38a4499ce38889a4dfc4c705b452049aebf0db4",
          "sha256": "5048209c55041a3ecaec9eca2be6c0e584eb9d38eb8e5bbbbb9dc1355ea11d99",
          "sha1": "12b3fe51b88775bd85c65bda814637beb427c69f",
          "md5": "beda0cf4d5b5760ad6347d50c43bfeb9"
        }
      ]
    }
  ]
}
