{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.5.1/lib-0.5.1.module",
    "group": "nz.eloque.compose-kit",
    "module": "lib",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.5.1.aar",
          "size": 301885,
          "sha512": "bc61db488eec7c35565f5edb2f80b000da34846f95882673d692d772b56f79a560790a5c6d3c9cc1586dfdcd5bf27796bbff68aac037d72266d6886cd891ef4f",
          "sha256": "ac9233655aef1dec9fb0ac18a44c0fa929800e3bb374c318aaea946504e36560",
          "sha1": "8ba1a4e49c277bc0c827b7fe9426f94293014857",
          "md5": "d1352730559f093283482cbf4c4981f5"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha22"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.5.1.aar",
          "size": 301885,
          "sha512": "bc61db488eec7c35565f5edb2f80b000da34846f95882673d692d772b56f79a560790a5c6d3c9cc1586dfdcd5bf27796bbff68aac037d72266d6886cd891ef4f",
          "sha256": "ac9233655aef1dec9fb0ac18a44c0fa929800e3bb374c318aaea946504e36560",
          "sha1": "8ba1a4e49c277bc0c827b7fe9426f94293014857",
          "md5": "d1352730559f093283482cbf4c4981f5"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lib-android-0.5.1-sources.jar",
          "url": "lib-android-0.5.1-sources.jar",
          "size": 38776,
          "sha512": "f6c02ba1443dc871816b2ef470bcd0fe0c45f8b0c98a2be28a6c5862a7f5c906554f0046d69ececb63c4f75abac6bc1fbe2b95e293d18cd2f0b430ea11e14c14",
          "sha256": "7c077598411f8107c71bd6cf72218a6803c2f73ff522d6f0622c604d53c947ed",
          "sha1": "86a4384f115cc09a52d2c46268abce9ccf6fd8fd",
          "md5": "23d4f4562edd1d825ad9140957e770ee"
        }
      ]
    }
  ]
}
