{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.5.9/lib-0.5.9.module",
    "group": "nz.eloque.compose-kit",
    "module": "lib",
    "version": "0.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "lib-wasm-js-0.5.9.klib",
          "url": "lib-wasm-js-0.5.9.klib",
          "size": 233781,
          "sha512": "cafcfadb01e96361e9d4d8cfb5d5f219b7e5b19ddeb94e3ca1660c1a132ea56b6c647963328b55354775d27166fc3e8c7e839312266400b68dbec6541240d5e7",
          "sha256": "c6c7a4e8f17f1d76bd593d070aa86f9cae0f32fddf1f4b60fa2417c83685e84e",
          "sha1": "caa83e106e5ff0b4be243a0d0887661055f4aa98",
          "md5": "e5d4a844a8007c5839e752d78fe15e11"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-wasm-js-0.5.9.klib",
          "url": "lib-wasm-js-0.5.9.klib",
          "size": 233781,
          "sha512": "cafcfadb01e96361e9d4d8cfb5d5f219b7e5b19ddeb94e3ca1660c1a132ea56b6c647963328b55354775d27166fc3e8c7e839312266400b68dbec6541240d5e7",
          "sha256": "c6c7a4e8f17f1d76bd593d070aa86f9cae0f32fddf1f4b60fa2417c83685e84e",
          "sha1": "caa83e106e5ff0b4be243a0d0887661055f4aa98",
          "md5": "e5d4a844a8007c5839e752d78fe15e11"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "lib-wasm-js-0.5.9-sources.jar",
          "url": "lib-wasm-js-0.5.9-sources.jar",
          "size": 34887,
          "sha512": "5f222770a8175f42da27f40f7b60ad1237e5a2ba01a586e466dbaf0cf4e286396c3bf6976d3bd66a79cb7ce3f5670d37a40f17b9d8c13755a84bfe9d9528802c",
          "sha256": "2d072bf5849d710c48c9ac5f3d6b34f7b33168c1dcd2108aeb2d8692f35c19ea",
          "sha1": "564f7e462e7d18556f399b8fb14de69ebddca991",
          "md5": "788122e7ec1e337b757089c88cf3990d"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-0.5.9.kotlin_resources.zip",
          "url": "lib-wasm-js-0.5.9-kotlin_resources.kotlin_resources.zip",
          "size": 15010,
          "sha512": "5e4e0b67298331bf91f25415d33fd0bec5824a71b0e73e69338b0e871887fcfae096a84e504bbb219c94694f2d21b59ba41bc124f37452a49af027751ca22a8f",
          "sha256": "ab367a3e847293f35bfe57fb940da5ca6933c435d692cdf1c6616afb16cfc85b",
          "sha1": "c79f6efad8eb80a6fb63210aa2e67d546f945301",
          "md5": "e20a06105bb1de11e308e9edb9922042"
        }
      ]
    }
  ]
}
