{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.5.0/lib-0.5.0.module",
    "group": "nz.eloque.compose-kit",
    "module": "lib",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.5.0.aar",
          "size": 302073,
          "sha512": "9aad4dce0c050ef8f0e818b83ccc8f94a5a805e1a211399eebb7dffa4864d203d3f3b71a28da6464b06b504c0138a4c536349b4f6d5b565a7c6d2f39ee51b7a8",
          "sha256": "c17deee7d73aefbf7651c7a7b5c97566caa08bc16cd16d12e24cd77fc581f811",
          "sha1": "0e69c8cb00050880e4635782a4822e9bed686bb4",
          "md5": "54b60fe388960f5f7872df7d6f618bf4"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha22"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.5.0.aar",
          "size": 302073,
          "sha512": "9aad4dce0c050ef8f0e818b83ccc8f94a5a805e1a211399eebb7dffa4864d203d3f3b71a28da6464b06b504c0138a4c536349b4f6d5b565a7c6d2f39ee51b7a8",
          "sha256": "c17deee7d73aefbf7651c7a7b5c97566caa08bc16cd16d12e24cd77fc581f811",
          "sha1": "0e69c8cb00050880e4635782a4822e9bed686bb4",
          "md5": "54b60fe388960f5f7872df7d6f618bf4"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lib-android-0.5.0-sources.jar",
          "url": "lib-android-0.5.0-sources.jar",
          "size": 38861,
          "sha512": "2353f4643db9a8d9c4b311053ed48b7cf351d25c00ce156f9f8de826200ea37b26cf91871412a6deebb273abdfcc3ec366d607f9a6918648f761c97e28196406",
          "sha256": "dae8193f3ce6422b556d40452dd08786fb615907ce2a5d036747d0c068f5b277",
          "sha1": "cb95d6d5456c73faa812baa620772bd3e07fca5d",
          "md5": "fd758ca5523a63c1120f472c505ccd40"
        }
      ]
    }
  ]
}
