{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.1/lib-0.1.1.module",
    "group": "nz.eloque.compose-kit",
    "module": "lib",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosArm64Main-0.1.1.klib",
          "url": "lib-iosarm64-0.1.1.klib",
          "size": 187585,
          "sha512": "066309f641a7dc6516f044bed157b9d2de541e815d5d28d4ac0a8ad7f25a41e7630d4168b5c1cd12a27833a6be80cd4a4aa4f20ca99acf08228baf54226e970e",
          "sha256": "0bce61b93d7e707c47006c8b8e69be2f66709ccd9fbcb545614a7a0ca3bb145e",
          "sha1": "2c0e9abe460abb2a84aecc433b595ff66d0142ff",
          "md5": "32e10dd96fd69a4eafee5af0337ceccb"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lib-iosarm64-0.1.1-sources.jar",
          "url": "lib-iosarm64-0.1.1-sources.jar",
          "size": 29155,
          "sha512": "1fbb9eb0927b28e262db68456e84d82e103b2ae37d72acdd8cea1eb9f33578436d542a7cf748151866192e8a12495606284f9aa969f912bfe127e4d4ea0e50c7",
          "sha256": "9dbb5f2d1aa87d0b9ba48aef30ea233e467b33d494f8646fc9c048a4b09b8650",
          "sha1": "3cfed685aa044e3f7906a43a5ebab25b58b2cfd2",
          "md5": "4bfd7ae9f4098fb4835f70336e067310"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-0.1.1.kotlin_resources.zip",
          "url": "lib-iosarm64-0.1.1-kotlin_resources.kotlin_resources.zip",
          "size": 14662,
          "sha512": "07b3f1a85c1db10c23536d0684d3602e218378b1ca9fe911a5db054db5a19c6fad00bca070907f3df28f3ac78343f4c3b28aaa97fe9c2c3257703bb429c8e044",
          "sha256": "ea10e16ef7944e99474ddbed3bd0e30f0a7331bd3bdd1837fc50e08eb7fde73f",
          "sha1": "bc994c7a7d975035cda3c51e3da563abb13f8e61",
          "md5": "06d068c0171cf34adafd61044f3a813a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosarm64-0.1.1-metadata.jar",
          "url": "lib-iosarm64-0.1.1-metadata.jar",
          "size": 2459,
          "sha512": "83dcac6872e2fb1e48431af9146a61f6f0de0af125f4111fe7cef41b5023ee8dc995258c564617919ff0537c625e613d08d903ba842b56a542058729ddfe6f0f",
          "sha256": "606525a5feb1101504747cf946b8b7d7d14a839ea83b7caf1d5c3d95a5371ede",
          "sha1": "b72bffa2c8d762a0bf229680f31eb75da9f379be",
          "md5": "5f826e765dc8842bac7505584251ce46"
        }
      ]
    }
  ]
}
