{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.5.9/lib-0.5.9.module",
    "group": "nz.eloque.compose-kit",
    "module": "lib",
    "version": "0.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.5.9.aar",
          "size": 319186,
          "sha512": "e0cc95f0ef2317dec6976b284cca858c1424caa2244f2729b6039162857db1a45df6ace7ddf46e2ac2d156f8454ce6a9851b0f4f3187fb00c00d7431ff66a489",
          "sha256": "37fd21a16bc8d46196e257797e2f9dd89261b08a0521476d518058f12f2acd50",
          "sha1": "c639f8302ee1b9289b1f04a1061339a28c254535",
          "md5": "06d8f0cf85fb0ed6a74c56c86ad159cf"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha24"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.5.9.aar",
          "size": 319186,
          "sha512": "e0cc95f0ef2317dec6976b284cca858c1424caa2244f2729b6039162857db1a45df6ace7ddf46e2ac2d156f8454ce6a9851b0f4f3187fb00c00d7431ff66a489",
          "sha256": "37fd21a16bc8d46196e257797e2f9dd89261b08a0521476d518058f12f2acd50",
          "sha1": "c639f8302ee1b9289b1f04a1061339a28c254535",
          "md5": "06d8f0cf85fb0ed6a74c56c86ad159cf"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lib-android-0.5.9-sources.jar",
          "url": "lib-android-0.5.9-sources.jar",
          "size": 40398,
          "sha512": "3be4bd9428122f67d618388efe47bb1502536781b3a994784d14cc23ca0eff09335e0b8003b5276c63c5eb89c6fef72c8b4f4ab50ec4c9f001768c9c6b325e8c",
          "sha256": "e8bf8adde70091e659853c2d2cffc22fbf81e6188397f5b37f564f2b2fdb8caa",
          "sha1": "abec853f09a5b47cd936a4191ba6c3cba5b9cca0",
          "md5": "d502efc7e8dce63248a86f81603e72de"
        }
      ]
    }
  ]
}
