{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.5.4/lib-0.5.4.module",
    "group": "nz.eloque.compose-kit",
    "module": "lib",
    "version": "0.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.5.4.aar",
          "size": 318362,
          "sha512": "e3117077e7921128beec02f3cb6be7007882bf77db8d3263313f2381ed8d66734d9e5525a1f1ca20048db96f9ac87a954d115a9220cceb2df2c4ca815fb374d1",
          "sha256": "3059917c18e6de616c48975d1a78219efcb98a4f969f1e5026acac30413b6be9",
          "sha1": "c49cd3734112ab36205fa96620a1b516cbecd38c",
          "md5": "601014ba4da2fe0fbc401610e6f33466"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha24"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.5.4.aar",
          "size": 318362,
          "sha512": "e3117077e7921128beec02f3cb6be7007882bf77db8d3263313f2381ed8d66734d9e5525a1f1ca20048db96f9ac87a954d115a9220cceb2df2c4ca815fb374d1",
          "sha256": "3059917c18e6de616c48975d1a78219efcb98a4f969f1e5026acac30413b6be9",
          "sha1": "c49cd3734112ab36205fa96620a1b516cbecd38c",
          "md5": "601014ba4da2fe0fbc401610e6f33466"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lib-android-0.5.4-sources.jar",
          "url": "lib-android-0.5.4-sources.jar",
          "size": 40296,
          "sha512": "e57fdd94fb4d9de1d230b9a3af672aa4b5bd95ae0e813cf5faa9621bafef65587d4c8526ca83da2333f7c4e7b65bede118de0ff6c35e0f6680c57bdcd5c50598",
          "sha256": "56d8909f4a2020764a48fd24d920aa9e7167bf8aee58d4e3399d0a0f5d7a9840",
          "sha1": "fd9ebd7bee871393dcc0d5067033d470dab2821e",
          "md5": "fc4596f97e1d2d9a757effac5a8850fe"
        }
      ]
    }
  ]
}
