{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.2.0/lib-0.2.0.module",
    "group": "nz.eloque.compose-kit",
    "module": "lib",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.2.0.aar",
          "size": 282236,
          "sha512": "f6d72c9d0fe7b72e7aee14bd0b31fd85601d89a8d59a1b68311f0410dba99e3b52a4003d306b94dc3dc4b841597d764b4b3b2bdf11c959d7ec874c8e121bc242",
          "sha256": "43dd95396d93ded18b14eb0e8f2db27e6aac48e8d29cf346214c6feb8d2fb447",
          "sha1": "d70cc9220b8fe7dad6b7cf98e03b4455729984a0",
          "md5": "577d8cead972762cc20adb6484076840"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha21"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.2.0.aar",
          "size": 282236,
          "sha512": "f6d72c9d0fe7b72e7aee14bd0b31fd85601d89a8d59a1b68311f0410dba99e3b52a4003d306b94dc3dc4b841597d764b4b3b2bdf11c959d7ec874c8e121bc242",
          "sha256": "43dd95396d93ded18b14eb0e8f2db27e6aac48e8d29cf346214c6feb8d2fb447",
          "sha1": "d70cc9220b8fe7dad6b7cf98e03b4455729984a0",
          "md5": "577d8cead972762cc20adb6484076840"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lib-android-0.2.0-sources.jar",
          "url": "lib-android-0.2.0-sources.jar",
          "size": 35911,
          "sha512": "10cd100c6ba28c38c2705f40c833f29af2dd211da39821127461d30adcc6cdcac85892caad63beac02a69c79525720185b0b60b2a6a76584ab4c2480a4c9c088",
          "sha256": "3bf0e3bd38e91f6077e21a464804c4e7d980298dabe603afba767a148ea341fa",
          "sha1": "9d650d9345c3455a9c1aeb5d3349dbf91ba8d3f7",
          "md5": "b45420f5d63317079ba334a3dadcf79b"
        }
      ]
    }
  ]
}
