{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.0/lib-0.1.0.module",
    "group": "nz.eloque.compose-kit",
    "module": "lib",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosSimulatorArm64Main-0.1.0.klib",
          "url": "lib-iossimulatorarm64-0.1.0.klib",
          "size": 185026,
          "sha512": "bfdc030ba1ff868f7886825d80fcce1b21ffb152aef91e8ea67cf21a7e4135d14d7a0fe8e236814fe99caa3194632afe84cdd5fe7141ccc0e7786f623ed61348",
          "sha256": "eb196ceeac9838a68a24e055107248135bac587ab3ee25f077c478dec4201696",
          "sha1": "869c6021c7b7d4218168b36fbac635308fb57d6d",
          "md5": "3733104f6ec236c14c6659f9b0083531"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lib-iossimulatorarm64-0.1.0-sources.jar",
          "url": "lib-iossimulatorarm64-0.1.0-sources.jar",
          "size": 29035,
          "sha512": "eb9bf9bcf828360e13618bf782cfb56723a830412966163d2ec172f0381ff5099f7d9f45ca09c3cc684d34b214b3f972d546531c64fa5d5ff8b36010b114a608",
          "sha256": "ace286e47285d123ec4a94318a7f784f6ed8cb52b171361e00bf34c585f01d63",
          "sha1": "f13e655344edfeee2ca51cacce451e2ea24791a8",
          "md5": "44f1a7f16a5fa21a146d079e467317c7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-0.1.0.kotlin_resources.zip",
          "url": "lib-iossimulatorarm64-0.1.0-kotlin_resources.kotlin_resources.zip",
          "size": 14662,
          "sha512": "07b3f1a85c1db10c23536d0684d3602e218378b1ca9fe911a5db054db5a19c6fad00bca070907f3df28f3ac78343f4c3b28aaa97fe9c2c3257703bb429c8e044",
          "sha256": "ea10e16ef7944e99474ddbed3bd0e30f0a7331bd3bdd1837fc50e08eb7fde73f",
          "sha1": "bc994c7a7d975035cda3c51e3da563abb13f8e61",
          "md5": "06d068c0171cf34adafd61044f3a813a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iossimulatorarm64-0.1.0-metadata.jar",
          "url": "lib-iossimulatorarm64-0.1.0-metadata.jar",
          "size": 2459,
          "sha512": "83dcac6872e2fb1e48431af9146a61f6f0de0af125f4111fe7cef41b5023ee8dc995258c564617919ff0537c625e613d08d903ba842b56a542058729ddfe6f0f",
          "sha256": "606525a5feb1101504747cf946b8b7d7d14a839ea83b7caf1d5c3d95a5371ede",
          "sha1": "b72bffa2c8d762a0bf229680f31eb75da9f379be",
          "md5": "5f826e765dc8842bac7505584251ce46"
        }
      ]
    }
  ]
}
