{
  "formatVersion": "1.1",
  "component": {
    "group": "nz.eloque.compose-kit",
    "module": "lib",
    "version": "0.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-metadata-0.5.4.jar",
          "url": "lib-0.5.4.jar",
          "size": 24450,
          "sha512": "8769923c694e775e784b94b3d2fbf71345b936c57a95c44b3555c74c84f1562a960aabc62cb7b41f6ee27826b0055dfde65dac8a7c1a123c6b40f3c715b5ff6b",
          "sha256": "3c2e49a6e59d718bafe6e179780661dcac795e68b1b9c1ba058380bbe5b7ba73",
          "sha1": "929ea9a8d4e9525c0e3b22e9de771aa50dc96352",
          "md5": "d6a40cbb483d14b083de0d637eed3baa"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "lib-kotlin-0.5.4-sources.jar",
          "url": "lib-0.5.4-sources.jar",
          "size": 33989,
          "sha512": "213221441a382cbf010af0d78d5d4cb992a9979401f9f476feec3c4d08ca9027f147bf77a2a042d37a08bbb575b29293b8c8f41a4f34af33894ade48fa6a3e83",
          "sha256": "8e9ea948101ae4b07c1de1224fb5a1297d8beeed12e296185e2cf8011b05883f",
          "sha1": "4071068567be16637fdc0b115a9b5b3c5c84cd57",
          "md5": "892da87efe2fe5327bbd8ce562776032"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lib-android/0.5.4/lib-android-0.5.4.module",
        "group": "nz.eloque.compose-kit",
        "module": "lib-android",
        "version": "0.5.4"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lib-android/0.5.4/lib-android-0.5.4.module",
        "group": "nz.eloque.compose-kit",
        "module": "lib-android",
        "version": "0.5.4"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lib-android/0.5.4/lib-android-0.5.4.module",
        "group": "nz.eloque.compose-kit",
        "module": "lib-android",
        "version": "0.5.4"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosarm64/0.5.4/lib-iosarm64-0.5.4.module",
        "group": "nz.eloque.compose-kit",
        "module": "lib-iosarm64",
        "version": "0.5.4"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosarm64/0.5.4/lib-iosarm64-0.5.4.module",
        "group": "nz.eloque.compose-kit",
        "module": "lib-iosarm64",
        "version": "0.5.4"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosarm64/0.5.4/lib-iosarm64-0.5.4.module",
        "group": "nz.eloque.compose-kit",
        "module": "lib-iosarm64",
        "version": "0.5.4"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iosarm64/0.5.4/lib-iosarm64-0.5.4.module",
        "group": "nz.eloque.compose-kit",
        "module": "lib-iosarm64",
        "version": "0.5.4"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iossimulatorarm64/0.5.4/lib-iossimulatorarm64-0.5.4.module",
        "group": "nz.eloque.compose-kit",
        "module": "lib-iossimulatorarm64",
        "version": "0.5.4"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iossimulatorarm64/0.5.4/lib-iossimulatorarm64-0.5.4.module",
        "group": "nz.eloque.compose-kit",
        "module": "lib-iossimulatorarm64",
        "version": "0.5.4"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iossimulatorarm64/0.5.4/lib-iossimulatorarm64-0.5.4.module",
        "group": "nz.eloque.compose-kit",
        "module": "lib-iossimulatorarm64",
        "version": "0.5.4"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-iossimulatorarm64/0.5.4/lib-iossimulatorarm64-0.5.4.module",
        "group": "nz.eloque.compose-kit",
        "module": "lib-iossimulatorarm64",
        "version": "0.5.4"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../lib-wasm-js/0.5.4/lib-wasm-js-0.5.4.module",
        "group": "nz.eloque.compose-kit",
        "module": "lib-wasm-js",
        "version": "0.5.4"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../lib-wasm-js/0.5.4/lib-wasm-js-0.5.4.module",
        "group": "nz.eloque.compose-kit",
        "module": "lib-wasm-js",
        "version": "0.5.4"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../lib-wasm-js/0.5.4/lib-wasm-js-0.5.4.module",
        "group": "nz.eloque.compose-kit",
        "module": "lib-wasm-js",
        "version": "0.5.4"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../lib-wasm-js/0.5.4/lib-wasm-js-0.5.4.module",
        "group": "nz.eloque.compose-kit",
        "module": "lib-wasm-js",
        "version": "0.5.4"
      }
    }
  ]
}
