{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.1.1/lib-0.1.1.module",
    "group": "nz.eloque.compose-kit",
    "module": "lib",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.1.1.aar",
          "size": 280975,
          "sha512": "64f5a8c35f2bb0fd1e2ba84ea55de779442f701da01a8f779875ab7eba6247312ba9b944d7cec47650bc6ef8208bccb425f302ca38010a86f912c6c3e8b48a37",
          "sha256": "575182c7bbc907a854f4c9f8b50ea2397709ee561c1f84693d7d78ceb7efc231",
          "sha1": "837c7510312af992cfa9abe17c2d1f2d00917691",
          "md5": "3004d36d465113d37c5ae795abeafb38"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha21"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib.aar",
          "url": "lib-android-0.1.1.aar",
          "size": 280975,
          "sha512": "64f5a8c35f2bb0fd1e2ba84ea55de779442f701da01a8f779875ab7eba6247312ba9b944d7cec47650bc6ef8208bccb425f302ca38010a86f912c6c3e8b48a37",
          "sha256": "575182c7bbc907a854f4c9f8b50ea2397709ee561c1f84693d7d78ceb7efc231",
          "sha1": "837c7510312af992cfa9abe17c2d1f2d00917691",
          "md5": "3004d36d465113d37c5ae795abeafb38"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lib-android-0.1.1-sources.jar",
          "url": "lib-android-0.1.1-sources.jar",
          "size": 35244,
          "sha512": "21afc7ddb1ce43207464f9f9b0ee5e5bd1f11c89fe57cfc6120df9115debed9c78c1db9201f00dfb64daf7782d1dbfbdc45b828902072070d052ff8656cfcbfd",
          "sha256": "70875862b021a67d8d9f6005f8dce7f781112b544f8783d9e433056231462ce2",
          "sha1": "c56e63049274931567d58c8f7540d9b8143f61b7",
          "md5": "16adac455c4990b33bfe78f2a97c6fdf"
        }
      ]
    }
  ]
}
