{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/0.5.8/lib-0.5.8.module",
    "group": "nz.eloque.compose-kit",
    "module": "lib",
    "version": "0.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "lib-wasm-js-0.5.8.klib",
          "url": "lib-wasm-js-0.5.8.klib",
          "size": 232461,
          "sha512": "97375a71d516e59625fe2de2569f1c605a5fc02fa46981f7e60b54e6350fdf81067e515a79fa5bde09bfe994b2f992500cc3a2ae1729415efe701d1f819c6a64",
          "sha256": "6c804fa119e1d955b964d5a41e4d97a57eca6e7cb8681480fd39ef9519e1b8a0",
          "sha1": "bd206152a70498eda7fe19d20d0700b432e18d5c",
          "md5": "8de3cee609ee9b12ed892d8cac0468c7"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-wasm-js-0.5.8.klib",
          "url": "lib-wasm-js-0.5.8.klib",
          "size": 232461,
          "sha512": "97375a71d516e59625fe2de2569f1c605a5fc02fa46981f7e60b54e6350fdf81067e515a79fa5bde09bfe994b2f992500cc3a2ae1729415efe701d1f819c6a64",
          "sha256": "6c804fa119e1d955b964d5a41e4d97a57eca6e7cb8681480fd39ef9519e1b8a0",
          "sha1": "bd206152a70498eda7fe19d20d0700b432e18d5c",
          "md5": "8de3cee609ee9b12ed892d8cac0468c7"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "lib-wasm-js-0.5.8-sources.jar",
          "url": "lib-wasm-js-0.5.8-sources.jar",
          "size": 34757,
          "sha512": "c1c2e5c40b778b7ccbd352da7d38e975ee49702ead6592c28519e6a571ab6210de850791ac0fd831f92d575f29a08a18c208fa6a0c546b90afa738527fe67504",
          "sha256": "a2eb1b2cab81a2fb0ae8f20e54b583e5a645f89d42aac6cd9cd976b01bfca374",
          "sha1": "41dee0ce4fe4a70ba0f84d43d9170d4457dd182a",
          "md5": "c8cb8c4ab16d9aa4570e4ee08b82d6c5"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-0.5.8.kotlin_resources.zip",
          "url": "lib-wasm-js-0.5.8-kotlin_resources.kotlin_resources.zip",
          "size": 15010,
          "sha512": "5e4e0b67298331bf91f25415d33fd0bec5824a71b0e73e69338b0e871887fcfae096a84e504bbb219c94694f2d21b59ba41bc124f37452a49af027751ca22a8f",
          "sha256": "ab367a3e847293f35bfe57fb940da5ca6933c435d692cdf1c6616afb16cfc85b",
          "sha1": "c79f6efad8eb80a6fb63210aa2e67d546f945301",
          "md5": "e20a06105bb1de11e308e9edb9922042"
        }
      ]
    }
  ]
}
